--- 
apiVersion: v1
kind: Secret
metadata:
  name: jfrogdockercredential
  namespace: dev
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnb3VtZ3VlODEuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImFtWnliMmRrYjJOclpYSmpjbVZrWlc1MGFXRnNPbGRoYldGcmIzVnNRRjh0T1RNMU13PT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
