apiVersion: v1
kind: Service
metadata:
  name:  goumgue-dwp-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: goumgue-dwp
  ports:
  - nodePort: 30001
    port: 8000
    targetPort: 8000
